# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Inshorts Autoupdate
on:
  push:
    paths:
      - .github/workflows/inshorts.yml # Only run a new workflow every time this file (muzli.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '*/5 * * * *' # every 5min

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: |
            git config --global user.name "mrblade"
            git config --global user.email "bullet_harsimran@yahoo.com"
            git add inshorts.json
            git commit --amend -m "Inshorts autoupdated"
            git push -f
