name: Muzli

on:
  push:
    paths:
      - .github/workflows/muzli.yml # Only run a new workflow every time this file (muzli.yaml) file changes
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '*/5 * * * *' # every 5min

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: # This workflow has 3 steps
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v2
      # The third step is a Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch data 
        uses: githubocto/flat@v3
        with:
          http_url: https://beta.api.muz.li/v1/feed/muzli?limit=20&sort=created # The data to fetch every 5 minutes
          downloaded_filename: muzli.json # The http_url gets saved and renamed in our repository as btc-price.json
          mask: true # optional param to mask the source http_url from the commit. Look at README for more options
